# Generated by Django 4.2.4 on 2023-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=3)),
                ('Rut', models.CharField(max_length=12)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=12)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
    ]
