# Generated by Django 4.2.4 on 2023-10-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_denuncia_latitud_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='Latitud_Longitud',
            field=models.CharField(max_length=100),
        ),
    ]
