# Generated by Django 4.2.4 on 2023-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_denuncia_latitud_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='Latitud_Longitud',
            new_name='Latitud',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Longitud',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
