# Generated by Django 4.2.4 on 2023-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_latitud_longitud_denuncia_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='Agresion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Direccion_Agresion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Fecha',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Hora',
            field=models.CharField(default=8, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='Motivo',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
    ]
