# Generated by Django 4.2.4 on 2023-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_denuncia_agresion_denuncia_direccion_agresion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='Longitud_Latitud',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
